name: Call a reusable workflow -ci

on:
  push:
    branches:
    - main
jobs:
  call-workflow-passing-data:
    uses: azawsdevops/github-reusable-modules/.github/workflows/ci.yaml@main
    with:
      component: cart