
name: Cart CICD 
run-name: Cart CICD 
on:
  push:
    branches:
    - main
jobs:
  ci:
    uses: azawsdevops/github-reusable-modules/.github/workflows/deploy.yaml@main
    with:
      component: cart
      