name: Cart helm deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    uses: azawsdevops/github-reusable-modules/.github/workflows/deploy.yaml@main
    with:
      component: cart
