name: Cart CICD - Main Branch
run-name: Cart CICD - Main Branch
on:
  push:
    branches:
    - main
    with:
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
jobs:
  ci:
    uses: azawsdevops/github-reusable-modules/.github/workflows/ci.yaml@main
    with:
      component: cart
      appType: nodejs

  deploy:
    uses: azawsdevops/github-reusable-modules/.github/workflows/deploy.yaml@main
    with:
      component: cart
      
      
      
      
      